@host = http://localhost:5018

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MjBlNmYwNy1kNjJlLTQwMWYtYTNiNC1mZjZhZjE5MGM3NzAiLCJnaXZlbl9uYW1lIjoiSmVucyIsImZhbWlseV9uYW1lIjoiU2VybmEiLCJqdGkiOiI2NjViZTYyNS1mMzViLTQ4YjMtOGJkYy02ZDc4ZjE1Mjk2ZTciLCJleHAiOjE2NzIwODE2MzQsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.U9aP5rIfsAZgtut72VymR_EgiS2HQNRDDtHGMJa8kDs